-- ========================================================
-- 🐾 PetCare (반려동물 AI 헬스케어 플랫폼) DDL Script
-- Database: Supabase PostgreSQL
-- Total Tables: 30 Tables (Kopang-Scale Enterprise Schema)
-- ========================================================

-- 1. 회원 테이블 (users)
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(100) UNIQUE NOT NULL,
    password            VARCHAR(255) NOT NULL,
    nickname            VARCHAR(50) NOT NULL,
    profile_image_url   TEXT,
    provider            VARCHAR(20) DEFAULT 'LOCAL' NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 사용자 권한 (user_roles)
CREATE TABLE IF NOT EXISTS user_roles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_name           VARCHAR(30) NOT NULL
);

-- 3. 소셜 연동 계정 (user_social_accounts)
CREATE TABLE IF NOT EXISTS user_social_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider            VARCHAR(20) NOT NULL,
    provider_id         VARCHAR(100) NOT NULL,
    connected_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 약관 동의 이력 (user_terms_agreements)
CREATE TABLE IF NOT EXISTS user_terms_agreements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    terms_type          VARCHAR(50) NOT NULL,
    is_agreed           BOOLEAN NOT NULL,
    agreed_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. JWT 리프레시 토큰 (refresh_tokens)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token               VARCHAR(500) UNIQUE NOT NULL,
    expiry_date         TIMESTAMP NOT NULL
);

-- 6. 사용자 알림 내역 (user_notifications)
CREATE TABLE IF NOT EXISTS user_notifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title               VARCHAR(150) NOT NULL,
    content             TEXT NOT NULL,
    notification_type   VARCHAR(50) NOT NULL,
    is_read             BOOLEAN DEFAULT FALSE NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. 축종 마스터 (pet_species)
CREATE TABLE IF NOT EXISTS pet_species (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(20) UNIQUE NOT NULL,
    name_ko             VARCHAR(50) NOT NULL
);

-- 8. 품종 마스터 (pet_breeds)
CREATE TABLE IF NOT EXISTS pet_breeds (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_code        VARCHAR(20) NOT NULL,
    name_ko             VARCHAR(50) NOT NULL,
    name_en             VARCHAR(50)
);

-- 9. 반려동물 메인 (pets)
CREATE TABLE IF NOT EXISTS pets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name                VARCHAR(50) NOT NULL,
    species             VARCHAR(20) NOT NULL,
    breed               VARCHAR(50),
    birth_date          DATE,
    gender              VARCHAR(20),
    weight              DOUBLE PRECISION,
    image_url           TEXT,
    is_primary          BOOLEAN DEFAULT FALSE NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. 반려동물 건강 프로필 (pet_health_profiles)
CREATE TABLE IF NOT EXISTS pet_health_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    allergies           TEXT,
    underlying_diseases TEXT,
    is_neutered         BOOLEAN DEFAULT FALSE,
    vaccination_history TEXT
);

-- 11. 체중 변화 히스토리 (pet_weight_histories)
CREATE TABLE IF NOT EXISTS pet_weight_histories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    weight              DOUBLE PRECISION NOT NULL,
    measured_at         DATE DEFAULT CURRENT_DATE NOT NULL
);

-- 12. 환부 카테고리 마스터 (symptom_categories)
CREATE TABLE IF NOT EXISTS symptom_categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(50) UNIQUE NOT NULL,
    name_ko             VARCHAR(50) NOT NULL
);

-- 13. 환부별 증상 체크박스 마스터 (symptoms)
CREATE TABLE IF NOT EXISTS symptoms (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code       VARCHAR(50) NOT NULL,
    symptom_name        VARCHAR(100) NOT NULL,
    display_order       INT DEFAULT 0
);

-- 14. 수의학 백과 마스터 (medical_encyclopedia)
CREATE TABLE IF NOT EXISTS medical_encyclopedia (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_code        VARCHAR(50) UNIQUE NOT NULL,
    disease_name_ko     VARCHAR(100) NOT NULL,
    cause_description   TEXT,
    home_care_guide     TEXT
);

-- 15. Vision AI 모델 질환 정보 (vision_disease_models)
CREATE TABLE IF NOT EXISTS vision_disease_models (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_code        VARCHAR(50) NOT NULL,
    model_version       VARCHAR(20) NOT NULL,
    default_risk_level  VARCHAR(20) NOT NULL
);

-- 16. AI 진단 기록 메인 (diagnosis_records)
CREATE TABLE IF NOT EXISTS diagnosis_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    affected_area       VARCHAR(50) NOT NULL,
    symptoms_json       TEXT,
    description         TEXT,
    image_url           TEXT NOT NULL,
    vision_result_json  TEXT NOT NULL,
    risk_level          VARCHAR(20) NOT NULL, -- OBSERVATION, CAUTION, EMERGENCY
    rag_report          TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 17. 진단 이미지 상세 (diagnosis_images)
CREATE TABLE IF NOT EXISTS diagnosis_images (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis_id        BIGINT NOT NULL REFERENCES diagnosis_records(id) ON DELETE CASCADE,
    image_url           TEXT NOT NULL,
    bounding_box_json   TEXT
);

-- 18. 증상 경과 비교 메인 (timeline_compares)
CREATE TABLE IF NOT EXISTS timeline_compares (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    prev_diagnosis_id   BIGINT NOT NULL REFERENCES diagnosis_records(id) ON DELETE CASCADE,
    curr_diagnosis_id   BIGINT NOT NULL REFERENCES diagnosis_records(id) ON DELETE CASCADE,
    recovery_status     VARCHAR(20) NOT NULL, -- IMPROVED, STABLE, WORSENED
    comparison_report   TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 19. 경과 관찰 피드백 (timeline_feedbacks)
CREATE TABLE IF NOT EXISTS timeline_feedbacks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timeline_compare_id BIGINT NOT NULL REFERENCES timeline_compares(id) ON DELETE CASCADE,
    user_satisfaction_score INT,
    vet_opinion_text    TEXT
);

-- 20. 경과 관찰 재진단 리마인더 (timeline_reminders)
CREATE TABLE IF NOT EXISTS timeline_reminders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    scheduled_date      DATE NOT NULL,
    is_sent             BOOLEAN DEFAULT FALSE NOT NULL
);

-- 21. 24시 응급 동물병원 (hospitals)
CREATE TABLE IF NOT EXISTS hospitals (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    address             VARCHAR(255) NOT NULL,
    phone               VARCHAR(30),
    latitude            DOUBLE PRECISION NOT NULL,
    longitude           DOUBLE PRECISION NOT NULL,
    is_emergency_24h    BOOLEAN DEFAULT TRUE NOT NULL
);

-- 22. 동물병원 영업시간 (hospital_operating_hours)
CREATE TABLE IF NOT EXISTS hospital_operating_hours (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id         BIGINT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    day_of_week         VARCHAR(10) NOT NULL,
    open_time           TIME,
    close_time          TIME
);

-- 23. 동물병원 진료과목 (hospital_departments)
CREATE TABLE IF NOT EXISTS hospital_departments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id         BIGINT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    department_name     VARCHAR(50) NOT NULL
);

-- 24. 단골 동물병원 북마크 (hospital_bookmarks)
CREATE TABLE IF NOT EXISTS hospital_bookmarks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hospital_id         BIGINT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 25. 실시간 펫 뉴스 (news_items)
CREATE TABLE IF NOT EXISTS news_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(255) NOT NULL,
    origin_link         TEXT UNIQUE NOT NULL,
    description         TEXT,
    pub_date            TIMESTAMP,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 26. 뉴스 카테고리 (news_categories)
CREATE TABLE IF NOT EXISTS news_categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(30) NOT NULL,
    name_ko             VARCHAR(50) NOT NULL
);

-- 27. 커뮤니티 게시글 (posts)
CREATE TABLE IF NOT EXISTS posts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    pet_id              BIGINT REFERENCES pets(id) ON DELETE SET NULL,
    diagnosis_record_id BIGINT REFERENCES diagnosis_records(id) ON DELETE SET NULL,
    title               VARCHAR(150) NOT NULL,
    content             TEXT NOT NULL,
    view_count          INT DEFAULT 0 NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 28. 게시글 첨부 이미지 (post_images)
CREATE TABLE IF NOT EXISTS post_images (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    image_url           TEXT NOT NULL
);

-- 29. 커뮤니티 댓글 (comments)
CREATE TABLE IF NOT EXISTS comments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id           BIGINT REFERENCES comments(id) ON DELETE CASCADE,
    content             TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 30. 게시글 좋아요 (post_likes)
CREATE TABLE IF NOT EXISTS post_likes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 설정 (조회 및 검색 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_pets_user_id ON pets(user_id);
CREATE INDEX IF NOT EXISTS idx_diagnosis_pet_id ON diagnosis_records(pet_id);
CREATE INDEX IF NOT EXISTS idx_timeline_pet_id ON timeline_compares(pet_id);
CREATE INDEX IF NOT EXISTS idx_hospitals_location ON hospitals(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_user_social_provider ON user_social_accounts(provider, provider_id);
